# Configuration file for the player written in YAML. Loadable to a
# python dictionary (hash table) using yaml.load(file) with PyYAML.

visual:
  fullscreen: false
  fullscreen_width:
  fullscreen_height:
  window_width: 640
  window_height: 480

control:
  forward:
    - w
    - UP
  backward:
    - s
    - DOWN
  left:
    - a
    - LEFT
  right:
    - d
    - RIGHT
  jump:
    - SPACE
    -
  menu:
    - ESCAPE
    -

  mouse_sensitivity: 0.3

debug:
  debug_mode: true
